---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    API_KEY: AgCe8S6454gKan+k5JAg2VZDySIbJ8IblChWx3+2n1gw6uo3q8Sak0SynT4g7grOsiDqzzdKtlmSMks2re/KL3YdEiNx179AduoexxE22uWpV68EG2VJSq7VHP/fb3mB6tqjTQkg6zQ4y/kZQ4VsOkIi1pHDQxE29XxzfvDcVMOFM1Vg4G7viA02YOth/sQMO3z5YJkqOsu3jx9G3iJeb//wJjfAe4NpVlANNXEKNWjYmE6f4gXxkvmmCNXhnvfvBySGRVeNpIYzQ6q50jM3duxnejo5awr+7fmYpSpMoW5boOrOWUlkCO8yY96YwpitTi+h5zuR6iiLgezvrulacVfp4k+wnhnpbDbwwZp3UnI5GFupQdgYq3WIfEuGs6U3j1cAcA9Nptdml7XlDdGtA0PxtANgubTU96i3ubIr6CABg344G7wA/6N8lDe0eRYSRVexx2fF6WLd4fl02Y4/8MRbQ12+63bnfKVXs417kccmcE2VtzKgwSnhpr76xAnvnDZrHsrYvFYL4bSBfgzLlFNZu6c8D87ii972orucZmS+F3pAzNYIIjSu3ZQemMCksTNhPIeDVZa6XJaqku0R5fPSMtGJp0I4ubQHVsxCrMiLIIX/nTIR7Sr0PbQ1/GVuGE9+MR6H3P7ayGJ2SqmHEUXjsjc4UZQlAZsNhfohkn2LZehO+ZruR3WW3scZdPshxIRWPb/stvDUHCZTaEwZN5LMmtE=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: default
